package com.studentmanagement.system.model;

import lombok.Data;
import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.mapping.Document;

@Data
@Document(collection = "students")
public class Students {

    @Id
    private String id;  // Auto-generated by MongoDB

    private String studentId;
    private String firstName;
    private String lastName;
    private String fullName;
    private String email;
    private String GuardianName;
    private String GuardianContact;
    private String address;
    private String phoneNumber;
    private String dateOfBirth;
    private String enrollmentDate;
    private String className;
    private String weight;
    private String height;
    private String teacherId;

    // Image-related field
    private String profileImageUrl;  // Stores the URL or file path of the uploaded image
}